export const NEW_INVOICE_REQUEST = 'NEW_INVOICE_REQUEST'
export const NEW_INVOICE_SUCCESS = 'NEW_INVOICE_SUCCESS'
export const NEW_INVOICE_FAIL = 'NEW_INVOICE_FAIL'
export const NEW_INVOICE_RESET = 'NEW_INVOICE_RESET'

export const INVOICE_LIST_REQUEST = 'INVOICE_LIST_REQUEST'
export const INVOICE_LIST_SUCCESS = 'INVOICE_LIST_SUCCESS'
export const INVOICE_LIST_FAIL = 'INVOICE_LIST_FAIL'
export const INVOICE_LIST_RESET = 'INVOICE_LIST_RESET'

export const INVOICE_UPDATE_REQUEST = 'INVOICE_UPDATE_REQUEST'
export const INVOICE_UPDATE_SUCCESS = 'INVOICE_UPDATE_SUCCESS'
export const INVOICE_UPDATE_FAIL = 'INVOICE_UPDATE_FAIL'
export const INVOICE_UPDATE_RESET = 'INVOICE_UPDATE_RESET'

export const INVOICE_DELETE_REQUEST = 'INVOICE_DELETE_REQUEST'
export const INVOICE_DELETE_SUCCESS = 'INVOICE_DELETE_SUCCESS'
export const INVOICE_DELETE_FAIL = 'INVOICE_DELETE_FAIL'
export const INVOICE_DELETE_RESET = 'INVOICE_DELETE_RESET'