export const NEW_LEAD_REQUEST = 'NEW_LEAD_REQUEST'
export const NEW_LEAD_SUCCESS = 'NEW_LEAD_SUCCESS'
export const NEW_LEAD_FAIL = 'NEW_LEAD_FAIL'
export const NEW_LEAD_RESET = 'NEW_LEAD_RESET'

export const LEAD_LIST_REQUEST = 'LEAD_LIST_REQUEST'
export const LEAD_LIST_SUCCESS = 'LEAD_LIST_SUCCESS'
export const LEAD_LIST_FAIL = 'LEAD_LIST_FAIL'
export const LEAD_LIST_RESET = 'LEAD_LIST_RESET'

export const LEAD_UPDATE_REQUEST = 'LEAD_UPDATE_REQUEST'
export const LEAD_UPDATE_SUCCESS = 'LEAD_UPDATE_SUCCESS'
export const LEAD_UPDATE_FAIL = 'LEAD_UPDATE_FAIL'
export const LEAD_UPDATE_RESET = 'LEAD_UPDATE_RESET'

export const LEAD_DELETE_REQUEST = 'LEAD_DELETE_REQUEST'
export const LEAD_DELETE_SUCCESS = 'LEAD_DELETE_SUCCESS'
export const LEAD_DELETE_FAIL = 'LEAD_DELETE_FAIL'
export const LEAD_DELETE_RESET = 'LEAD_DELETE_RESET'