export const NEW_MEMBER_REQUEST = 'NEW_MEMBER_REQUEST'
export const NEW_MEMBER_SUCCESS = 'NEW_MEMBER_SUCCESS'
export const NEW_MEMBER_FAIL = 'NEW_MEMBER_FAIL'
export const NEW_MEMBER_RESET = 'NEW_MEMBER_RESET'