export const NEW_MEMBERSHIP_REQUEST = 'NEW_MEMBERSHIP_REQUEST'
export const NEW_MEMBERSHIP_SUCCESS = 'NEW_MEMBERSHIP_SUCCESS'
export const NEW_MEMBERSHIP_FAIL = 'NEW_MEMBERSHIP_FAIL'
export const NEW_MEMBERSHIP_RESET = 'NEW_MEMBERSHIP_RESET'

export const MEMBERSHIP_LIST_REQUEST = 'MEMBERSHIP_LIST_REQUEST'
export const MEMBERSHIP_LIST_SUCCESS = 'MEMBERSHIP_LIST_SUCCESS'
export const MEMBERSHIP_LIST_FAIL = 'MEMBERSHIP_LIST_FAIL'
export const MEMBERSHIP_LIST_RESET = 'MEMBERSHIP_LIST_RESET'

export const MEMBERSHIP_UPDATE_REQUEST = 'MEMBERSHIP_UPDATE_REQUEST'
export const MEMBERSHIP_UPDATE_SUCCESS = 'MEMBERSHIP_UPDATE_SUCCESS'
export const MEMBERSHIP_UPDATE_FAIL = 'MEMBERSHIP_UPDATE_FAIL'
export const MEMBERSHIP_UPDATE_RESET = 'MEMBERSHIP_UPDATE_RESET'

export const MEMBERSHIP_DELETE_REQUEST = 'MEMBERSHIP_DELETE_REQUEST'
export const MEMBERSHIP_DELETE_SUCCESS = 'MEMBERSHIP_DELETE_SUCCESS'
export const MEMBERSHIP_DELETE_FAIL = 'MEMBERSHIP_DELETE_FAIL'
export const MEMBERSHIP_DELETE_RESET = 'MEMBERSHIP_DELETE_RESET'