export const NEW_MEMBER_REQUEST = 'NEW_MEMBER_REQUEST'
export const NEW_MEMBER_SUCCESS = 'NEW_MEMBER_SUCCESS'
export const NEW_MEMBER_FAIL = 'NEW_MEMBER_FAIL'
export const NEW_MEMBER_RESET = 'NEW_MEMBER_RESET'

export const MEMBER_LIST_REQUEST = 'MEMBER_LIST_REQUEST'
export const MEMBER_LIST_SUCCESS = 'MEMBER_LIST_SUCCESS'
export const MEMBER_LIST_FAIL = 'MEMBER_LIST_FAIL'
export const MEMBER_LIST_RESET = 'MEMBER_LIST_RESET'

export const MEMBER_UPDATE_REQUEST = 'MEMBER_UPDATE_REQUEST'
export const MEMBER_UPDATE_SUCCESS = 'MEMBER_UPDATE_SUCCESS'
export const MEMBER_UPDATE_FAIL = 'MEMBER_UPDATE_FAIL'
export const MEMBER_UPDATE_RESET = 'MEMBER_UPDATE_RESET'

export const MEMBER_DELETE_REQUEST = 'MEMBER_DELETE_REQUEST'
export const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS'
export const MEMBER_DELETE_FAIL = 'MEMBER_DELETE_FAIL'
export const MEMBER_DELETE_RESET = 'MEMBER_DELETE_RESET'