export const NEW_SUPPLEMENT_REQUEST = 'NEW_SUPPLEMENT_REQUEST'
export const NEW_SUPPLEMENT_SUCCESS = 'NEW_SUPPLEMENT_SUCCESS'
export const NEW_SUPPLEMENT_FAIL = 'NEW_SUPPLEMENT_FAIL'
export const NEW_SUPPLEMENT_RESET = 'NEW_SUPPLEMENT_RESET'

export const SUPPLEMENT_LIST_REQUEST = 'SUPPLEMENT_LIST_REQUEST'
export const SUPPLEMENT_LIST_SUCCESS = 'SUPPLEMENT_LIST_SUCCESS'
export const SUPPLEMENT_LIST_FAIL = 'SUPPLEMENT_LIST_FAIL'
export const SUPPLEMENT_LIST_RESET = 'SUPPLEMENT_LIST_RESET'

export const SUPPLEMENT_UPDATE_REQUEST = 'SUPPLEMENT_UPDATE_REQUEST'
export const SUPPLEMENT_UPDATE_SUCCESS = 'SUPPLEMENT_UPDATE_SUCCESS'
export const SUPPLEMENT_UPDATE_FAIL = 'SUPPLEMENT_UPDATE_FAIL'
export const SUPPLEMENT_UPDATE_RESET = 'SUPPLEMENT_UPDATE_RESET'

export const SUPPLEMENT_DELETE_REQUEST = 'SUPPLEMENT_DELETE_REQUEST'
export const SUPPLEMENT_DELETE_SUCCESS = 'SUPPLEMENT_DELETE_SUCCESS'
export const SUPPLEMENT_DELETE_FAIL = 'SUPPLEMENT_DELETE_FAIL'
export const SUPPLEMENT_DELETE_RESET = 'SUPPLEMENT_DELETE_RESET'