export const NEW_TRAINER_REQUEST = 'NEW_TRAINER_REQUEST'
export const NEW_TRAINER_SUCCESS = 'NEW_TRAINER_SUCCESS'
export const NEW_TRAINER_FAIL = 'NEW_TRAINER_FAIL'
export const NEW_TRAINER_RESET = 'NEW_TRAINER_RESET'

export const TRAINER_LIST_REQUEST = 'TRAINER_LIST_REQUEST'
export const TRAINER_LIST_SUCCESS = 'TRAINER_LIST_SUCCESS'
export const TRAINER_LIST_FAIL = 'TRAINER_LIST_FAIL'
export const TRAINER_LIST_RESET = 'TRAINER_LIST_RESET'

export const TRAINER_UPDATE_REQUEST = 'TRAINER_UPDATE_REQUEST'
export const TRAINER_UPDATE_SUCCESS = 'TRAINER_UPDATE_SUCCESS'
export const TRAINER_UPDATE_FAIL = 'TRAINER_UPDATE_FAIL'
export const TRAINER_UPDATE_RESET = 'TRAINER_UPDATE_RESET'

export const TRAINER_DELETE_REQUEST = 'TRAINER_DELETE_REQUEST'
export const TRAINER_DELETE_SUCCESS = 'TRAINER_DELETE_SUCCESS'
export const TRAINER_DELETE_FAIL = 'TRAINER_DELETE_FAIL'
export const TRAINER_DELETE_RESET = 'TRAINER_DELETE_RESET'