export const NEW_LOGIN_REQUEST = 'NEW_LOGIN_REQUEST'
export const NEW_LOGIN_SUCCESS = 'NEW_LOGIN_SUCCESS'
export const NEW_LOGIN_FAIL = 'NEW_LOGIN_FAIL'
export const NEW_LOGIN_RESET = 'NEW_LOGIN_RESET'