export const NEW_LOGIN_REQUEST = 'NEW_LOGIN_REQUEST'
export const NEW_LOGIN_SUCCESS = 'NEW_LOGIN_SUCCESS'
export const NEW_LOGIN_FAIL = 'NEW_LOGIN_FAIL'
export const NEW_LOGIN_RESET = 'NEW_LOGIN_RESET'

export const NEW_LOGOUT_REQUEST = 'NEW_LOGOUT_REQUEST'
export const NEW_LOGOUT_SUCCESS = 'NEW_LOGOUT_SUCCESS'
export const NEW_LOGOUT_FAIL = 'NEW_LOGOUT_FAIL'
export const NEW_LOGOUT_RESET = 'NEW_LOGOUT_RESET'